version: "3"

services:
  sandbox:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: sandbox
    hostname: sandbox
    env_file:
      - ./env/ldap.env
      - ./env/pam.env
    ports:
      - 2222:22
